name: Pull Request
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Jest
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn
      - run: yarn test
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Jest
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: yarn
      - run: yarn build